services:
 api:
  build:
   context: .
   dockerfile: api
  container_name: api
  expose: 
   - "8000"
  restart: always
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    interval: 30s
    timeout: 5s
    retries: 3
  volumes:
   - ${DATA_SERVER_STORAGE_BLOCK}:/data
 nginx:
  build:
   context: .
   dockerfile: nginx
  ports:
  - "80:80"
  depends_on: 
  - api
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost/"]
    interval: 30s
    timeout: 5s
    retries: 3
  restart: always

 ui:
  build:
   context: .
   dockerfile: ui
  container_name: ui
  expose:
   - "5500"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:5500/health"]
    interval: 30s
    timeout: 5s
    retries: 3
  restart: always

 monitor:
  build:
   context: .
   dockerfile: monitor
  container_name: monitor
  expose:
   - "6000"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:6000/health"]
    interval: 30s
    timeout: 5s
    retries: 3
  volumes:
   - ${DATA_SERVER_STORAGE_BLOCK}:/data
  restart: always
