services:
 api:
  build:
   context: .
   dockerfile: api
  container_name: api
  expose: 
   - "8000"
  restart: always
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
    interval: 30s
    timeout: 5s
    retries: 3
 nginx:
  build:
   context: .
   dockerfile: nginx
  ports:
  - "80:80"
  depends_on: 
  - api
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost/"]
    interval: 30s
    timeout: 5s
    retries: 3
  restart: always